COGNITO_DOMAIN="https://eu-central-10olb8byvy.auth.eu-central-1.amazoncognito.com"
COGNITO_CLIENT_ID="19ua9pvuqj2haf98vdgdsgod5q"
REDIRECT_URI="https://cc2025-frontend-gea3frg0exbpbgcp.northeurope-01.azurewebsites.net"
BACKEND_URL="https://cc2025-backend-feh4axf9hkcybcbs.northeurope-01.azurewebsites.net"